# Generated by Django 4.2.18 on 2025-02-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fragility', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('photoUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial_address', models.CharField(max_length=255)),
                ('final_address', models.CharField(max_length=255)),
                ('cost_aprox', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('tittle', models.CharField(max_length=255)),
                ('business_id', models.BigIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('photo_url', models.URLField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportWorker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('type_of_transport', models.CharField(max_length=255)),
                ('transport_id', models.CharField(max_length=255)),
                ('photo_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
            ],
        ),
    ]
